server:
  port: 3001

registry:
  driver: memory

policy:
  opaUrl: "http://localhost:8181/v1/data/translation/allow"

lineage:
  emit: true
  namespace: "translation.layer"

security:
  readOnly: true
  rateLimitPerMinute: 600

context:
  maxPicklistValues: 200
  includeValidationRules: true